TRAIN_TEST_RATIO: 0.2
PVALUE_THRESHOLD: 0.05
TARGET_COLUMN: class
EXPECTED_ACCURACY_THRESHOLD: 0.7
OVERFIT_UNDERFIT_THRESHOLD: 0.05
MODEL_EVALUATION_CHANGED_THRESHOLD: 0.02
APP_HOST: "0.0.0.0"
APP_PORT: 8080


